### ISSUE TITLE
Melhorar ambiente para desenvolvimento

### ISSUE THREAD

**Issue by SabinoGs** [fga-eps-mds/2017.2-MerendaMais#175]
### Descrição
Eu como desenvolvedor desejo que o ambiente de desenvolvimento permita que eu utilize outros meios, além do `smartphone` para facilitar o desenvolvimento da aplicação. 

### Label
- [x] Technical
- [x] Improvement

### Tasks
- [ ] Permitir execução do ambiente de desenvolvimento sem a necessidade de rede, ou 
- [ ] Permitir o desenvolvimento através do navegador.
- [ ] Refazer o docker da aplicação
